### PR TITLE
Added Graph to TensorBoard

### PR DESCRIPTION
**Pull request by DrewNF**
At the end was pretty easy to add the graph to tensorboard, only a line.
I think is really helpful to see the graph and understand better the
structure.
I also extract the txt file of the structure of the Inception model
that is the starting one (If you run the pull request and go to
visualise the graph you can see it in the left part of the graph).
Bests
screenshot 2016-07-20 18 30 48

screenshot 2016-07-20 18 30 13

### CODE REVIEW

**Comment by Russell91** [comment]
Wow, looks great, but do you mind merging master and making the change via the pull request so that I can merge directly?

**Comment by DrewNF** [comment]
Is this the Pull Request or I'm getting wrong what you want?
I send you a mail, maybe is in the spam folder.  Bests

**Comment by Russell91** [comment]
Yeah, so if you click on changes above though you'll notice there are lots of changes that don't involve the graph part. I already accepted the other changes with a few modifications.

**Comment by Russell91** [comment]
Merged in separate pr

**Pull request closed without merging**
